### ISSUE TITLE
Error calling cucumberJson.attach in beforeFeature 

### ISSUE THREAD

**Issue by nabsofken** [webdriverio-community/wdio-cucumberjs-json-reporter#91]
I am calling cucumberJson.attach('Running in before Feature function') in a beforeFeature method and I get the following error. Using version 4.4.0
```
Cannot read properties of undefined (reading 'steps')
[0-0]     err: {
[0-0]       "type": "TypeError",
[0-0]       "message": "Cannot read properties of undefined (reading 'steps')",
[0-0]       "stack":
[0-0]           TypeError: Cannot read properties of undefined (reading 'steps')
[0-0]               at CucumberJsJsonReporter.getCurrentStep (/Desktop/cui-e2e-automation/node_modules/wdio-cucumberjs-json-reporter/lib/reporter.ts:303:32)
[0-0]               at CucumberJsJsonReporter.cucumberJsAttachment (/Desktop/cui-e2e-automation/node_modules/wdio-cucumberjs-json-reporter/lib/reporter.ts:334:34)
[0-0]               at process.emit (node:events:390:28)
[0-0]               at process.emit (node:domain:475:12)
[0-0]               at process.emit (/Desktop/cui-e2e-automation/node_modules/ts-node/node_modules/source-map-support/source-map-support.js:516:21)
[0-0]               at Function.attach (/Desktop/cui-e2e-automation/node_modules/wdio-cucumberjs-json-reporter/lib/reporter.ts:56:19)
```

**Comment by wswebcreation** [comment]
Hi @nabsofken 

The `beforeFeature` runs before a Cucumber Feature, meaning there is completely no context, the feature has not been read. So that's the reason why it breaks
